---
# INFO: https://pre-commit.com/hooks.html
# NOTE: Borrowed a bunch from https://github.com/Yelp/swagger_zipkin/blob/master/.pre-commit-config.yaml
repos:
-   repo: git://github.com/pre-commit/pre-commit-hooks
    sha: v0.9.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
    -   id: check-yaml
    -   id: debug-statements
    # -   id: name-tests-test
    -   id: flake8
        args: ['--max-line-length=200']
    -   id: requirements-txt-fixer
    -   id: check-executables-have-shebangs
    -   id: fix-encoding-pragma
    -   id: check-yaml
    -   id: check-json
        files: \.(bowerrc|jshintrc|json)$
-   repo: git://github.com/pre-commit/mirrors-isort
    sha: '4b74ac14df891a0958e5355c5e60d110f0bc45e0'
    hooks:
    -   id: isort
