version: "2"

services:
  scarlett_master:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # ssh enabled
        SCARLETT_ENABLE_SSHD: 0
        SCARLETT_ENABLE_DBUS: 'true'
        SCARLETT_BUILD_GNOME: 'true'
        # Signal s6 to stop when finished all run.d scripts. Important for CI builds.
        TRAVIS_CI: 'false'
    environment:
      SERVER_LOG_MINIMAL: 1
      SERVER_APP_NAME: scarlett-master
      COMPOSE_PROJECT_NAME: scarlett-master
      S6_KILL_FINISH_MAXTIME: 1
      S6_KILL_GRACETIME: 1
      SERVER_WORKER_PROCESSES: 1
      # NOTE: This enables SSHD access inside of the container for dev purposes
      # 1 = false
      # 0 = true
      SCARLETT_ENABLE_SSHD: 0
      SCARLETT_ENABLE_DBUS: 'true'
      SCARLETT_BUILD_GNOME: 'true'
      TRAVIS_CI: 'false'
    volumes:
    - ./:/home/pi/dev/bossjones-github/scarlett_os:rw
    ports:
    - "2222:22"
