version: '2'

services:
  testing:
    extends:
      file: ./docker-compose-devtools.yml
    image: scarlett_os_master
    environment:
      SERVER_LOG_MINIMAL: 1
      SERVER_APP_NAME: jhbuild-scarlett-os
      S6_KILL_FINISH_MAXTIME: 1
      S6_KILL_GRACETIME: 1
      SERVER_WORKER_PROCESSES: 1
      # Ensure that Python outputs everything that's printed inside
      # the application rather than buffering it.
      PYTHONUNBUFFERED: 1
    stdin_open: true
    tty: true
    depends_on:
        - master
    entrypoint:
      - "/docker_entrypoint.sh"
      - make 
      - test-travis