# scarlett_master:
#   build: .
#   environment:
#     SERVER_LOG_MINIMAL: 1
#     SERVER_APP_NAME: jhbuild-scarlett-os
#     S6_KILL_FINISH_MAXTIME: 1
#     S6_KILL_GRACETIME: 1
#     SERVER_WORKER_PROCESSES: 1
#   volumes:
#   - ./:/home/pi/dev/bossjones-github/scarlett_os:rw

version: '2'

services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    image: scarlett_os_master
    working_dir: /home/pi/dev/bossjones-github/scarlett_os
    environment:
      SERVER_LOG_MINIMAL: 1
      SERVER_APP_NAME: jhbuild-scarlett-os
      S6_KILL_FINISH_MAXTIME: 1
      S6_KILL_GRACETIME: 1
      SERVER_WORKER_PROCESSES: 1
      # Ensure that Python outputs everything that's printed inside
      # the application rather than buffering it.
      PYTHONUNBUFFERED: 1
    stdin_open: true
    tty: true
    entrypoint:
      - "/docker_entrypoint.sh"
      - "/bin/bash"
    volumes:
      - ./:/home/pi/dev/bossjones-github/scarlett_os:rw

  anaconda:
      image: scarlett_os_master
      ports:
          - "19360:19360"
      environment:
        SERVER_LOG_MINIMAL: 1
        SERVER_APP_NAME: jhbuild-scarlett-os
        S6_KILL_FINISH_MAXTIME: 1
        S6_KILL_GRACETIME: 1
        SERVER_WORKER_PROCESSES: 1
        # Ensure that Python outputs everything that's printed inside
        # the application rather than buffering it.
        PYTHONUNBUFFERED: 1
      stdin_open: true
      tty: true
      # volumes:
          # - /Users/malcolm/.config/sublime_text_3/Packages/Anaconda:/opt/anaconda
          # OLD # - '/Users/malcolm/Library/Application Support/Sublime Text 3/Packages/Anaconda:/opt/anaconda'
          # - "/Users/malcolm/Library/Application Support/Sublime Text 3/Packages/Anaconda:/opt/anaconda"
      depends_on:
          - master
      entrypoint: "/opt/anaconda/anaconda_server/docker/start python3 19360 docker_project /home/pi/dev/bossjones-github/scarlett_os"


# volumes:
#   config:
#     external: false
