# Omitted values in this section will be auto detected using freegeoip.io

# Location required to calculate the time the sun rises and sets.
# Coordinates are also used for location for weather related automations.
# Google Maps can be used to determine more precise GPS coordinates.
latitude: 40.7056308
longitude: -73.9780034

# pocketsphinx config options source: https://github.com/cmusphinx/pocketsphinx/blob/1fdc9ccb637836d45d40956e745477a2bd3b470a/doc/pocketsphinx_continuous.1
pocketsphinx:
    hmm: /home/pi/.virtualenvs/scarlett_os/share/pocketsphinx/model/en-us/en-us
    lm: /home/pi/dev/bossjones-github/scarlett_os/static/speech/lm/1473.lm
    dict: /home/pi/dev/bossjones-github/scarlett_os/static/speech/dict/1473.dic
    # Silence word transition probability
    silprob: 0.1
    # ********************************************************
    # FIXME: ????? THIS IS THE ORIG VALUE, do we need too set it back? 8/5/2018 # wip: 1e-4
    # Enable Graph Search | Boolean. Default: true
    # ********************************************************
    # Word insertion penalty
    wip: 0.0001
    device: plughw:CARD=Device,DEV=0
    # ********************************************************
    # FIXME: ????? THIS IS THE ORIG VALUE, do we need too set it back? 8/5/2018 # bestpath: 0
    # Enable Graph Search | Boolean. Default: true
    # ********************************************************
    bestpath: True
    # Enable Flat Lexicon Search | Default: true
    fwdflat: True
    # Evaluate acoustic model every N frames |  Integer. Range: 1 - 10 Default: 1
    dsratio: 1
    # Maximum number of HMMs searched per frame | Integer. Range: 1 - 100000 Default: 30000
    maxhmmpf: 3000


# Impacts weather/sunrise data
elevation: 665

# 'metric' for Metric System, 'imperial' for imperial system
unit_system: metric

# Pick yours from here:
# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
time_zone: America/New_York

# Name of the location where ScarlettOS Assistant is running
name: ScarlettOS

owner: "Hair Ron Jones"

keywords_list:
- 'scarlett'
- 'SCARLETT'

features:
- time

graphviz_debug_dir: /home/pi/dev/bossjones-github/scarlett_os/_debug
